In [ ]:
#Task 1
#from matplotlib import pyplot as plt
import cv2 as cv
from cv2 import waitKey
import numpy as np

img1 = np.zeros((50,50,3),np.uint8)
img2 = np.zeros((50,50,3),np.uint8)
img3 = np.zeros((50,50,3),np.uint8)
img4 = np.zeros((50,50,3),np.uint8)

img1[:,:] = (0,0,0)
img2[:,:] = (0,255,0)
img3[:,:] = (255,0,0)
img4[:,:] = (0,0,200)

hor1= np.hstack((img1,img2))
hor2 = np.hstack((img3,img4))
ver = np.vstack((hor1,hor2))

result = cv.resize(ver,(200,200))

cv.imshow("Result",result)

#--------- using Matplotlib ------------
##plt.imshow(img, cmap = 'gray')
##plt.tick_params(axis='y',left = False,labelleft = False)
##plt.xticks([0,50,100,150,200,255])
##plt.show()

waitKey(0)

In [ ]:
#Task 2
from sre_constants import SUCCESS
import cv2 as cv
from cv2 import waitKey
import numpy as np

#flags
r = 0
g = 0
h = 0
x = 0
s = 0
c = 0

cam = cv.VideoCapture(0)
cam.set(10,100)

result = cv.VideoWriter('CapturedVideo.avi', cv.VideoWriter_fourcc(*'MJPG'),10,(640,480))

while True:
    SUCCESS , img=cam.read()
    if s :
        result.write(img)
    if g :
        img = cv.cvtColor(img ,cv.COLOR_BGR2GRAY)
    if r :
        img = cv.rotate(img, cv.ROTATE_90_CLOCKWISE) 
    if h :
        img = cv.cvtColor(img, cv.COLOR_BGR2HSV) 
    if x :
        grey = cv.cvtColor(img ,cv.COLOR_BGR2GRAY)
        rotate = cv.rotate(img, cv.ROTATE_90_CLOCKWISE)
        hsv = cv.cvtColor(img, cv.COLOR_BGR2HSV) 
        cv.imshow("Rotated",rotate) 
        cv.imshow("Grey", grey) 
        cv.imshow("hsv",hsv) 

    cv.imshow("WebCam",img)
    input = cv.waitKey(1)


    if (input == ord('q')) or (input == ord('Q')) :
        if s :
            cam.release()
            result.release()
        break
    elif (input == ord('r')) or (input == ord('R')) :
        r,g,h = 1,0,0
    elif (input == ord('h')) or (input == ord('H')) :
        h,r,g, = 1,0,0
    elif (input == ord('g')) or (input == ord('G')) :
        g,r,h = 1,0,0
    elif (input == ord('x')) or (input == ord('X')) :
        x,g,r,h = 1,0,0,0
    elif (input == ord('z')) or (input == ord('Z')) :
        cv.destroyAllWindows()
        x,g,r,h = 0,0,0,0
    elif (input == ord('s')) or (input == ord('S')) :
        s = 1
    elif (input == ord('c')) or (input == ord('C')) :
        cv.imwrite(f'Image{" "}.png',img)


In [ ]:
#Task 3

In [ ]:
#Task 4
import copy
import cv2 as cv
from cv2 import waitKey
from cv2 import EVENT_MBUTTONDOWN
import numpy as np

def mouseclick(event,x,y,flags,params):
    global img
    global cache
    global org

    if event == cv.EVENT_LBUTTONDOWN:
        cache = copy.deepcopy(img)
        cv.circle(img,(x,y),30,(0,0,150),5)

    elif event == cv.EVENT_RBUTTONDOWN:
        img = copy.deepcopy(cache)
        cv.imshow(" ", img)

    elif event == cv.EVENT_MBUTTONDOWN:
        img = copy.deepcopy(org)
        cache=copy.deepcopy(org)
        cv.imshow(" ",img)

    else:
        print("Invalid Input")    

global img
global cache
global org

img = np.zeros((550,800,3),np.uint8)
img[:,:] = (0,0,0)

org = np.zeros((550,800,3),np.uint8)
org[:,:] = (0,0,0)

cv.putText(img, 'Press Q to quit', (50, 350),cv.FONT_HERSHEY_TRIPLEX,0.5,(255, 255, 255),1)
cv.putText(img, 'Circle : Left Click', (50, 400),cv.FONT_HERSHEY_TRIPLEX,0.5,(255, 255, 255),1)
cv.putText(img, 'Undo : Right Click', (50, 450),cv.FONT_HERSHEY_TRIPLEX,0.5,(255, 255, 255),1)
cv.putText(img, 'Clear : Middle Mouse Button', (50, 500),cv.FONT_HERSHEY_TRIPLEX,0.5,(255, 255, 255),1)
cv.putText(org, 'Press Q to quit', (50, 350),cv.FONT_HERSHEY_TRIPLEX,0.5,(255, 255, 255),1)
cv.putText(org, 'Circle : Left Click', (50, 400),cv.FONT_HERSHEY_TRIPLEX,0.5,(255, 255, 255),1)
cv.putText(org, 'Undo : Right Click', (50, 450),cv.FONT_HERSHEY_TRIPLEX,0.5,(255, 255, 255),1)
cv.putText(org, 'Clear : Middle Mouse Button', (50, 500),cv.FONT_HERSHEY_TRIPLEX,0.5,(255, 255, 255),1)

cache = copy.deepcopy(img)
cv.namedWindow(' ') 

while (1):
    cv.setMouseCallback(" ",mouseclick)
    cv.imshow(" ",img)
    input=cv.waitKey(1)
    if input == ord('q') or input == ord('Q'):
        break

    cv.imshow(" ",img)   

cv.destroyAllWindows()

In [1]:
#Task 5
import cv2 as cv
import numpy as np
from cv2 import waitKey

circles = np.zeros((4,2),np.int64)
c=0

def mouseclick(event,x,y,flags,params):
    global c
    if event == cv.EVENT_LBUTTONDOWN:
        circles[c] = x,y
        c+=1
        print(circles)


img = cv.imread('Resources/jhonsmith.jpg')

while True :

    if c == 4:
        width , height = 250,350
        pts1 = np.float32([circles[0],circles[1],circles[2],circles[3]])
        pts2 = np.float32([[0,0],[width,0],[0,height],[width,height]])
        matrix = cv.getPerspectiveTransform(pts1,pts2)
        imgOutput = cv.warpPerspective(img,matrix,(width,height))
        cv.imshow('Output Image ',imgOutput)

    for x in range (0,4):
        cv.circle(img,(circles[x][0],circles[x][1]),3,(0,255,0),cv.FILLED)

    cv.imshow('Original Image ',img)
    cv.setMouseCallback('Original Image ',mouseclick)
    cv.waitKey(1)

[[130 222]
 [  0   0]
 [  0   0]
 [  0   0]]
[[130 222]
 [694  84]
 [  0   0]
 [  0   0]]
[[130 222]
 [694  84]
 [216 567]
 [  0   0]]
[[130 222]
 [694  84]
 [216 567]
 [835 363]]


KeyboardInterrupt: 

: 